### ISSUE TITLE
WrappedToken.sol contract doesn't compile

### ISSUE THREAD

**Issue by Rizziepit** [Snowfork/polkadot-ethereum#321]
I'm running into the following compilation error when deploying our contracts to Truffle:
```
Compiling your contracts...
===========================
> Compiling ./contracts/BasicOutboundChannel.sol
> Compiling ./contracts/DOTApp.sol
> Compiling ./contracts/ERC20App.sol
> Compiling ./contracts/ETHApp.sol
> Compiling ./contracts/IncentivizedOutboundChannel.sol
> Compiling ./contracts/OutboundChannel.sol
> Compiling ./contracts/WrappedToken.sol

CompileError: @openzeppelin/contracts/token/ERC777/ERC777.sol:170:5: TypeError: Trying to override non-virtual function. Did you forget to add "virtual"?
    function burn(uint256 amount, bytes memory data) public override  {
    ^ (Relevant source part starts here and spans across multiple lines).
/home/riz/Projects/polkadot-ethereum/ethereum/contracts/WrappedToken.sol:29:5: Overriding function is here:
    function burn(uint256, bytes memory) public pure override  {
    ^ (Relevant source part starts here and spans across multiple lines).
,@openzeppelin/contracts/token/ERC777/ERC777.sol:246:5: TypeError: Trying to override non-virtual function. Did you forget to add "virtual"?
    function operatorBurn(address account, uint256 amount, bytes memory data, bytes memory operatorData) public override {
    ^ (Relevant source part starts here and spans across multiple lines).
/home/riz/Projects/polkadot-ethereum/ethereum/contracts/WrappedToken.sol:33:5: Overriding function is here:
    function operatorBurn(address, uint256, bytes memory, bytes memory) public pure override {
    ^ (Relevant source part starts here and spans across multiple lines).

Compilation failed. See above.
    at run (/home/riz/.config/yarn/global/node_modules/truffle/build/webpack:/packages/compile-solidity/run.js:53:1)
    at Object.sourcesWithDependencies (/home/riz/.config/yarn/global/node_modules/truffle/build/webpack:/packages/compile-solidity/index.js:117:58)
    at necessary (/home/riz/.config/yarn/global/node_modules/truffle/build/webpack:/packages/compile-solidity/index.js:70:1)
    at /home/riz/.config/yarn/global/node_modules/truffle/build/webpack:/packages/workflow-compile/index.js:33:1
    at async Promise.all (index 0)
    at compile (/home/riz/.config/yarn/global/node_modules/truffle/build/webpack:/packages/workflow-compile/index.js:23:1)
    at Object.compile (/home/riz/.config/yarn/global/node_modules/truffle/build/webpack:/packages/workflow-compile/index.js:66:45)
    at Object.compileAndSave (/home/riz/.config/yarn/global/node_modules/truffle/build/webpack:/packages/workflow-compile/index.js:92:45)
Truffle v5.1.62 (core: 5.1.62)
Node v14.15.4
```

**Comment by Rizziepit** [comment]
@vgeddes I'm guessing this was introduced by https://github.com/Snowfork/polkadot-ethereum/pull/271/

**Comment by Rizziepit** [comment]
Whoops I just needed to update my node dependencies with a `yarn install`
